In [3]:
import sys
import os

sys.path.append(os.path.abspath(".."))

In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split

from src.preprocessing import clean_data
from src.feature_engineering import create_features
from src.train_models import train_models
from src.evaluate_models import evaluate_models

In [9]:
df = pd.read_excel("../data/raw/credit_card.xlsx")
df.head()

,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,...,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Trans_Ct,Avg_Utilization_Ratio,Quarter,Year,Date_Leave
0,712672083,Existing Customer,65,F,0,High School,Married,Less than $40K,Blue,36,...,3,2,1438.3,747,691.3,24,0.519,none,2018,"none,2018"
1,713049933,Existing Customer,47,F,1,Graduate,Married,$40K - $60K,Silver,36,...,2,2,5756.0,0,5756.0,44,0.000,none,2018,"none,2018"
2,713049933,Existing Customer,48,F,1,Graduate,Married,$40K - $60K,Silver,48,...,6,2,5756.0,990,5756.0,25,0.170,none,2019,"none,2019"
3,713135883,Existing Customer,65,F,0,College,Married,Less than $40K,Blue,65,...,5,0,4315.0,393,3598.0,73,0.090,none,2019,"none,2019"
4,713135883,Existing Customer,64,F,0,College,Married,Less than $40K,Blue,53,...,3,0,4315.0,717,3598.0,51,0.166,none,2018,"none,2018"

In [10]:
df = clean_data(df)
df = create_features(df)

df.head()

,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,Total_Relationship_Count,...,Transactions_per_Month,Inactivity_and_Contact_Index,avg_revolving_per_trans,is_inactive,low_activity,low_utilization,High_Utilization_Flag,high_contact_count,open_to_buy_ratio,log_credit_limit
0,Existing Customer,46,F,3,High School,Married,$40K - $60K,Blue,48,4,...,0.897959,5,20.955556,0,1,0,0,0,0.531171,8.173293
1,Attrited Customer,58,M,0,College,Single,$40K - $60K,Blue,45,3,...,0.456522,4,114.409091,0,1,0,1,0,0.264173,8.137980
2,Attrited Customer,60,M,3,Graduate,Divorced,$60K - $80K,Silver,38,6,...,0.589744,6,73.791667,1,1,0,0,0,0.785446,9.019059
3,Attrited Customer,35,F,2,Uneducated,Single,Less than $40K,Blue,36,6,...,1.270270,4,16.333333,0,1,0,1,0,0.958228,7.313887
4,Existing Customer,50,F,2,High School,Married,Less than $40K,Blue,53,3,...,1.481481,3,2.864198,0,0,1,0,0,0.760307,8.048469

In [22]:
# Fix target (1 = churn)
y = 1 - df["Attrition_Flag_Existing Customer"]

# Features
X = df.drop("Attrition_Flag_Existing Customer", axis=1)

In [24]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [25]:
models = train_models(X_train, y_train)

models

C:\Users\user\credit-card-attrition-project\churn_env\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 2000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=2000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

{'logistic_regression': LogisticRegression(class_weight='balanced', max_iter=2000),
 'random_forest': RandomForestClassifier(n_estimators=200, random_state=42),
 'xgboost': GradientBoostingClassifier()}

In [26]:
metrics = evaluate_models(models, X_test, y_test)

metrics

{'logistic_regression': {'roc_auc': 1.0,
  'f1': 1.0,
  'recall': 1.0,
  'precision': 1.0},
 'random_forest': {'roc_auc': 1.0, 'f1': 1.0, 'recall': 1.0, 'precision': 1.0},
 'xgboost': {'roc_auc': 1.0, 'f1': 1.0, 'recall': 1.0, 'precision': 1.0}}

In [27]:
pd.DataFrame(metrics).T

                     roc_auc   f1  recall  precision
logistic_regression      1.0  1.0     1.0        1.0
random_forest            1.0  1.0     1.0        1.0
xgboost                  1.0  1.0     1.0        1.0